## gather函数 

In [2]:
import torch

In [3]:
# 对于y_hat的每一行，分别取其y0列，y1列
y_hat = torch.tensor([[0.1, 0.3, 0.6], [0.3, 0.2, 0.5]])
y = torch.LongTensor([0, 2])
y_hat.gather(1, y.view(-1, 1))

tensor([[0.1000],
        [0.5000]])

## 广播机制 

In [5]:
a = torch.tensor([[2,3,4], [5,3,1]])
b = torch.tensor([[2], [5]])
print(a, "\n", b, "\n", a / b)

tensor([[2, 3, 4],
        [5, 3, 1]]) 
 tensor([[2],
        [5]]) 
 tensor([[1, 1, 2],
        [1, 0, 0]])


In [6]:
c = torch.tensor([3,2,5])
print(a, "\n", c, "\n", a / c)

tensor([[2, 3, 4],
        [5, 3, 1]]) 
 tensor([3, 2, 5]) 
 tensor([[0, 1, 0],
        [1, 1, 0]])


In [7]:
d = torch.tensor(2)
print(a, "\n", d, "\n", a / d)

tensor([[2, 3, 4],
        [5, 3, 1]]) 
 tensor(2) 
 tensor([[1, 1, 2],
        [2, 1, 0]])


In [8]:
e = torch.tensor([1,2,3,4])
# Error:The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1
# print(a, "\n", e, "\n", a / e)

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 1