In [16]:
import torch as T
import numpy as np

## 创建一个零向量 

In [2]:
# 默认float32
ze1 = T.zeros(5)
ze1

tensor([0., 0., 0., 0., 0.])

In [4]:
# 改变零向量的类型
ze2 = T.zeros(5, dtype=T.int8)
ze2

tensor([0, 0, 0, 0, 0], dtype=torch.int8)

## 从列表创建向量 

In [5]:
t1 = T.tensor([1,2,3])
t1

tensor([1, 2, 3])

In [6]:
# 改变向量类型
t2 = T.tensor([1,2,3], dtype=T.float32)
t2

tensor([1., 2., 3.])

## torch中的range 

In [7]:
t3 = T.arange(6)
print(t3)
t4 = T.arange(3, 5)
print(t4)

tensor([0, 1, 2, 3, 4, 5])
tensor([3, 4])


## 判断是否torch中的向量 

In [9]:
print(T.is_tensor(t4))
print(T.is_storage(t4))
print(T.is_storage(t4.storage()))

True
False
True


## 改变torch向量中的类型

In [11]:
t5 = T.tensor([1.2, 3.3, 5.5, 6.6, 8.8])
print(t5)
print("dtype of t5: " + str(t5.dtype))

# 报错：dtype  is not writable
# t5.dtype = T.int32
# print(t5)
# print("dtype of t5: " + str(t5.dtype))

# .int()方法 .float()方法
# 向下取整
print(t5.int())
print(t5.int().float())

tensor([1.2000, 3.3000, 5.5000, 6.6000, 8.8000])
dtype of t5: torch.float32
tensor([1, 3, 5, 6, 8], dtype=torch.int32)
tensor([1., 3., 5., 6., 8.])


## tensor和Tensor的区别 

In [15]:
# Tensor是python类，是FloatTensor的别名，传入参数时用类中的__init__函数构造
t8 = T.Tensor([1,2])
print(t8)
t9 = T.Tensor((1,2,3))
print(t9)

tensor([1., 2.])
tensor([1., 2., 3.])


In [18]:
# tensor只是python函数
t10 = T.tensor([1,2])
print(t10, t10.type())
t11 = T.tensor([1., 2.])
print(t11, t11.type())
t12 = T.tensor([1,2], dtype=T.float64)
print(t12, t12.type())

tensor([1, 2]) torch.LongTensor
tensor([1., 2.]) torch.FloatTensor
tensor([1., 2.], dtype=torch.float64) torch.DoubleTensor


In [14]:
# 当构造函数传入一个整数...
t6 = T.tensor(3)
print(t6)
print(t6.type())
t7 = T.Tensor(3)
print(t7)
print(t7.type())

tensor(3)
torch.LongTensor
tensor([ 0.0000e+00,  0.0000e+00, -3.5218e+31])
torch.FloatTensor


## 随机化生成 

In [20]:
# 均匀分布 U(0, 1)
t13 = T.rand(5)
print(t13)

# 标准正态分布 N(0, 1)
t14 = T.randn(5)
print(t14)

# 标准正态分布
# TypeError: normal() received an invalid combination of arguments - got (int, int), but expected one of:
#  * (Tensor mean, Tensor std, torch.Generator generator, Tensor out)
#  * (Tensor mean, float std, torch.Generator generator, Tensor out)
#  * (float mean, Tensor std, torch.Generator generator, Tensor out)
#  * (float mean, float std, tuple of ints size, torch.Generator generator, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
# N(2, 3) size=(2,)
t15 = T.normal(2.0, 3.0, (2,))
print(t15)
# N(4, 5) size=(2, 3)
t16 = T.normal(4, 5, (2, 3))
print(t16)

tensor([0.3390, 0.6180, 0.3480, 0.1864, 0.2747])
tensor([-0.7176, -0.2029,  0.3582, -0.9103, -0.1446])
tensor([1.2932, 5.0290])
tensor([[5.6318, 2.3881, 6.8796],
        [3.7647, 6.7170, 3.8206]])


## 新建空Tensor和全值Tensor 

In [22]:
t17 = T.tensor([[1,2,3], [4,5,6]])
print(t17)
t18 = T.empty(t17.size())
print(t18)
t19 = T.empty_like(t18)
print(t19)
t20 = T.full(t17.size(), 3)
print(t20)
t21 = T.full_like(t17, 4)
print(t21)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([[3.3709e-06, 6.7407e+22, 1.0442e-08],
        [6.4832e-10, 1.0741e-05, 1.7679e-04]])
tensor([[3., 3., 3.],
        [3., 3., 3.]])
tensor([[4, 4, 4],
        [4, 4, 4]])


## Tensor类api 

In [33]:
t19 = T.tensor([[[1,2,3], [4,5,6]], [[7,8,9], [10, 11, 12]]])
print("size: ", t19.size())
print("number in the vector: ", T.numel(t19))
# print("t.view(2,3,1)", t19.view(1))
# 升维
print("unsqueeze at 1: ", t19.unsqueeze(3))
print("T.cat: ", T.cat((t19, t19), 2))

size:  torch.Size([2, 2, 3])
number in the vector:  12
unsqueeze at 1:  tensor([[[[ 1],
          [ 2],
          [ 3]],

         [[ 4],
          [ 5],
          [ 6]]],


        [[[ 7],
          [ 8],
          [ 9]],

         [[10],
          [11],
          [12]]]])
T.cat:  tensor([[[ 1,  2,  3,  1,  2,  3],
         [ 4,  5,  6,  4,  5,  6]],

        [[ 7,  8,  9,  7,  8,  9],
         [10, 11, 12, 10, 11, 12]]])


## 采数据 

In [49]:
# T.index_select
x = T.randn(3, 4)
print(x)
indices = T.tensor([0, 2])
print(T.index_select(x, 0, indices))
print(T.index_select(x, 1, indices))

# T.maksed_select
x = T.randn(3, 4)
print(x)
mask = x.ge(0.5)
print(mask)
print(T.masked_select(x, mask))

tensor([[-0.7590, -0.0937,  0.6554,  1.8314],
        [ 1.2193,  1.8789,  0.8606, -1.6536],
        [-0.7149, -0.3994, -0.8282,  0.0470]])
tensor([[-0.7590, -0.0937,  0.6554,  1.8314],
        [-0.7149, -0.3994, -0.8282,  0.0470]])
tensor([[-0.7590,  0.6554],
        [ 1.2193,  0.8606],
        [-0.7149, -0.8282]])
tensor([[-1.3025,  0.4671, -0.6238, -0.6365],
        [-0.1552, -0.2093,  0.8949, -0.6457],
        [ 1.8273, -2.1901,  0.2340, -0.1876]])
tensor([[False, False, False, False],
        [False, False,  True, False],
        [ True, False, False, False]])
tensor([0.8949, 1.8273])


## 与numpy的对接

In [42]:
x = np.arange(1,4)
t = T.from_numpy(x)
print(t)
print(t.numpy(), type(t.numpy()))

tensor([1, 2, 3], dtype=torch.int32)
[1 2 3] <class 'numpy.ndarray'>


## torch中的linspace和logspace 

In [43]:
print(T.linspace(2, 10, 9))
print(T.logspace(-10, 10, 5))

tensor([ 2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])
tensor([1.0000e-10, 1.0000e-05, 1.0000e+00, 1.0000e+05, 1.0000e+10])


## 随机整数排列向量 

In [44]:
print(T.randperm(8))

tensor([2, 0, 3, 1, 4, 7, 6, 5])


## 分块 

In [47]:
x = T.rand(4, 6)
print(x)
# 分成n个chunk
print(T.chunk(x, 2, 0))
print(T.chunk(x, 3, 1))
# 分成每个chunk中有n个向量
print(T.split(x, 2, 0))
print(T.split(x, 3, 1))

tensor([[0.9151, 0.7256, 0.4663, 0.0375, 0.5520, 0.0531],
        [0.0071, 0.9389, 0.4395, 0.1306, 0.3914, 0.2924],
        [0.2637, 0.7947, 0.7601, 0.4212, 0.4125, 0.1038],
        [0.4870, 0.1184, 0.8249, 0.0330, 0.2562, 0.7320]])
(tensor([[0.9151, 0.7256, 0.4663, 0.0375, 0.5520, 0.0531],
        [0.0071, 0.9389, 0.4395, 0.1306, 0.3914, 0.2924]]), tensor([[0.2637, 0.7947, 0.7601, 0.4212, 0.4125, 0.1038],
        [0.4870, 0.1184, 0.8249, 0.0330, 0.2562, 0.7320]]))
(tensor([[0.9151, 0.7256],
        [0.0071, 0.9389],
        [0.2637, 0.7947],
        [0.4870, 0.1184]]), tensor([[0.4663, 0.0375],
        [0.4395, 0.1306],
        [0.7601, 0.4212],
        [0.8249, 0.0330]]), tensor([[0.5520, 0.0531],
        [0.3914, 0.2924],
        [0.4125, 0.1038],
        [0.2562, 0.7320]]))
(tensor([[0.9151, 0.7256, 0.4663, 0.0375, 0.5520, 0.0531],
        [0.0071, 0.9389, 0.4395, 0.1306, 0.3914, 0.2924]]), tensor([[0.2637, 0.7947, 0.7601, 0.4212, 0.4125, 0.1038],
        [0.4870, 0.1184, 0.8249, 0

## 向量转置 

In [51]:
e = T.randn(2, 3)
print(e)
print(e.t())
print(e.transpose(1, 0))

tensor([[ 1.9375, -0.8770,  0.6281],
        [-0.7785,  0.4650, -0.7276]])
tensor([[ 1.9375, -0.7785],
        [-0.8770,  0.4650],
        [ 0.6281, -0.7276]])
tensor([[ 1.9375, -0.7785],
        [-0.8770,  0.4650],
        [ 0.6281, -0.7276]])


## 向量运算 

In [53]:
T.manual_seed(1234)
x = T.randn(2, 3)
print(x)

tensor([[ 0.0461,  0.4024, -1.0115],
        [ 0.2167, -0.6123,  0.5036]])


In [54]:
print(T.add(x, 20))

tensor([[20.0461, 20.4024, 18.9885],
        [20.2167, 19.3877, 20.5036]])


In [55]:
print(T.ceil(x))

tensor([[ 1.,  1., -1.],
        [ 1., -0.,  1.]])


In [56]:
print(T.floor(x))

tensor([[ 0.,  0., -2.],
        [ 0., -1.,  0.]])


In [57]:
print(T.exp(x))

tensor([[1.0472, 1.4954, 0.3637],
        [1.2420, 0.5421, 1.6547]])


In [58]:
print(T.sigmoid(x))

tensor([[0.5115, 0.5993, 0.2667],
        [0.5540, 0.3515, 0.6233]])


In [59]:
a = T.tensor([[1,2,3], [4,5,6]])
b = T.tensor([[1,2], [3, 4], [5,6]])
print(a * a)
print(a.mul(a))
print(a.mm(b))

tensor([[ 1,  4,  9],
        [16, 25, 36]])
tensor([[ 1,  4,  9],
        [16, 25, 36]])
tensor([[22, 28],
        [49, 64]])


## 排序 

In [61]:
x = T.randperm(6)
print(x)
print(T.sort(x))
print(x)

tensor([0, 3, 4, 1, 2, 5])
torch.return_types.sort(
values=tensor([0, 1, 2, 3, 4, 5]),
indices=tensor([0, 3, 4, 1, 2, 5]))
tensor([0, 3, 4, 1, 2, 5])


## View方法 

In [63]:
x = T.randn(4, 4)
print(x.size())
y = x.view(16)
print(y.size())
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(z.size())

torch.Size([4, 4])
torch.Size([16])
torch.Size([2, 8])


In [65]:
a = T.randn(1, 2, 3, 4)
print(a.size())
b = a.transpose(1, 2)  # Swaps 2nd and 3rd dimension
print(b.size())
c = a.view(1, 3, 2, 4)  # Does not change tensor layout in memory
print(c.size())
print(T.equal(b, c))

torch.Size([1, 2, 3, 4])
torch.Size([1, 3, 2, 4])
torch.Size([1, 3, 2, 4])
False


In [67]:
print(a)
print(b)
print(c)

tensor([[[[-2.1834,  0.3668,  0.7667,  0.0190],
          [ 0.0220,  1.1532, -0.3393,  0.1559],
          [-1.0248, -0.3781,  0.9257,  0.9247]],

         [[ 0.1825, -0.0737,  0.3147, -1.0369],
          [ 1.0534,  0.3692,  0.0628, -0.3297],
          [-1.7970,  0.8728,  0.7670, -0.1138]]]])
tensor([[[[-2.1834,  0.3668,  0.7667,  0.0190],
          [ 0.1825, -0.0737,  0.3147, -1.0369]],

         [[ 0.0220,  1.1532, -0.3393,  0.1559],
          [ 1.0534,  0.3692,  0.0628, -0.3297]],

         [[-1.0248, -0.3781,  0.9257,  0.9247],
          [-1.7970,  0.8728,  0.7670, -0.1138]]]])
tensor([[[[-2.1834,  0.3668,  0.7667,  0.0190],
          [ 0.0220,  1.1532, -0.3393,  0.1559]],

         [[-1.0248, -0.3781,  0.9257,  0.9247],
          [ 0.1825, -0.0737,  0.3147, -1.0369]],

         [[ 1.0534,  0.3692,  0.0628, -0.3297],
          [-1.7970,  0.8728,  0.7670, -0.1138]]]])
